FROM maven:3

MAINTAINER Florian Lopes <florian.lopes@outlook.com>

RUN mkdir -p /build

COPY pom.xml ./

# Install needed tests dependencies, enable Docker to cache dependencies
RUN mvn install clean --fail-never -B -DfailIfNoTests=false

RUN ls /build
RUN ls 

COPY . /build/

WORKDIR /build
